# Generated by Django 5.2.5 on 2025-08-28 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GPGKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_public_key",
                    models.TextField(
                        blank=True,
                        db_column="public_key",
                        unique=True,
                        verbose_name="Public key",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("emails", models.TextField(blank=True)),
                ("verification_message", models.CharField(blank=True, max_length=255)),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Verified"),
                ),
                ("primary", models.BooleanField(default=False, verbose_name="Primary")),
                (
                    "temporary",
                    models.BooleanField(default=False, verbose_name="Temporary"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gpg_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemporaryGPGKey",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gpg.gpgkey",),
        ),
        migrations.AddConstraint(
            model_name="gpgkey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("primary", True)),
                fields=("user", "primary"),
                name="unique_primary_key_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="gpgkey",
            constraint=models.UniqueConstraint(fields=("fingerprint",), name="unique_fingerprint"),
        ),
    ]
