# Generated by Django 5.2.5 on 2025-08-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpg", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpgkey",
            name="verification_message",
            field=models.CharField(blank=True, db_column="verification_message", max_length=255),
        ),
        migrations.RenameField(
            model_name="gpgkey",
            old_name="verification_message",
            new_name="_verification_message",
        ),
    ]
