# Generated by Django 5.2.5 on 2025-08-31 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_delete_gpgkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
