# Generated by Django 5.2.5 on 2025-08-31 14:27

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Ballot = apps.get_model("voting", "Ballot")
    for row in Ballot.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_auto_20250831_1627"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
