# Generated by Django 5.2.5 on 2025-08-31 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0004_auto_20250831_1627"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ballot",
            name="ballot_id",
        ),
        migrations.RemoveField(
            model_name="ballot",
            name="checksum",
        ),
        migrations.RemoveField(
            model_name="ballot",
            name="selection",
        ),
        migrations.RemoveField(
            model_name="ballot",
            name="token",
        ),
        migrations.AddField(
            model_name="ballot",
            name="result",
            field=models.JSONField(default="{}"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ballot",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
