# Generated by Django 5.2.5 on 2025-09-03 13:41

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0005_remove_ballot_ballot_id_remove_ballot_checksum_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("query_parameters", models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email",
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(default="FR", max_length=2),
        ),
    ]
