# Generated by Django 5.2.5 on 2025-12-28 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0006_query_remove_customuser_email_customuser_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerCryptoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "private_key_pem",
                    models.TextField(blank=True, help_text="Clé privée (Format PEM)"),
                ),
                (
                    "public_key_pem",
                    models.TextField(blank=True, help_text="Clé publique (Format PEM)"),
                ),
            ],
            options={
                "verbose_name": "Configuration Cryptographique",
            },
        ),
        migrations.RemoveField(
            model_name="tokenattribution",
            name="user",
        ),
        migrations.RemoveField(
            model_name="tokenattribution",
            name="vote",
        ),
        migrations.AddField(
            model_name="ballot",
            name="server_signature",
            field=models.TextField(
                default="", help_text="Signature Base64 prouvant l'authenticité"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ballot",
            name="token",
            field=models.CharField(
                db_index=True, default="", max_length=512, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ballot",
            name="vote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ballots",
                to="voting.vote",
            ),
        ),
        migrations.CreateModel(
            name="VoterStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blinded_message_hash",
                    models.TextField(
                        blank=True,
                        help_text="Hash du message aveuglé pour vérifier l'idempotence",
                        null=True,
                    ),
                ),
                (
                    "generated_signature",
                    models.TextField(
                        blank=True,
                        help_text="Signature renvoyée au client (Base64)",
                        null=True,
                    ),
                ),
                ("has_signed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voting.vote"
                    ),
                ),
            ],
            options={
                "verbose_name": "Statut de signature de l'électeur",
                "unique_together": {("user", "vote")},
            },
        ),
        migrations.DeleteModel(
            name="Token",
        ),
        migrations.DeleteModel(
            name="TokenAttribution",
        ),
    ]
