# Generated by Django 5.2.5 on 2025-12-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0007_servercryptoconfig_remove_tokenattribution_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServerCryptoConfig",
        ),
        migrations.AddField(
            model_name="vote",
            name="private_key_pem",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="public_key_pem",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
