# Generated by Django 5.2.5 on 2026-01-03 09:11

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    CustomUser = apps.get_model("voting", "CustomUser")
    for row in CustomUser.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0009_customuser_uuid_alter_ballot_result"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
